In [30]:
import numpy as np
import nnfs
import matplotlib.pyplot as plt
import nnfs
from nnfs.datasets import spiral_data


NameError: name 'spiral' is not defined

In [20]:
class LayerDense:
    

    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

a = np.zeros((1, 3))
print(a)


[[0. 0. 0.]]


In [21]:
n_inputs = 2
n_neurons = 4
weights = 0.01 * np.random.randn(n_inputs, n_neurons)
biases = np.zeros((1, n_neurons))

print(weights)
print(biases)

[[-0.00103219  0.00410599  0.00144044  0.01454273]
 [ 0.00761038  0.00121675  0.00443863  0.00333674]]
[[0. 0. 0. 0.]]


In [31]:
X, y = spiral_data(samples=100, classes=3)


In [32]:
dense1 = LayerDense(2,3)

In [33]:
dense1.forward(X)

In [35]:
print(dense1.output[:5])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0832220e-05 -7.2641757e-05 -8.2110644e-05]
 [-2.3288900e-05 -1.5646787e-04 -1.5816503e-04]
 [-3.0686224e-05 -2.0563323e-04 -2.4215934e-04]
 [-1.4825159e-05 -9.8157187e-05 -1.9212626e-04]]
